name: pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - run: PATH=/usr/lib/llvm-18/bin:$PATH make cli web
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - id: deploy
        uses: actions/deploy-pages@v4
